[PHP]
; Habilitar subidas de archivos
file_uploads = On

; Tamaño máximo permitido para un archivo subido (aumenta este valor según sea necesario)
upload_max_filesize = 100M

; Tamaño máximo permitido para todos los datos POST (aumenta este valor según sea necesario)
post_max_size = 100M

; Tiempo máximo de ejecución de cada script, en segundos
max_execution_time = 300

; Tiempo máximo de análisis de los datos de entrada, en segundos
max_input_time = 300

; Límite de memoria
memory_limit = 256M

; Otros ajustes de configuración necesarios
output_buffering = 4096
max_input_vars = 1000
